stages:
  - vet
  - test
  - build
  - docker-build

default:
  image: warrior7089/go-docker:latest

services:  
  - name: docker:20.10.21-dind 
    command: ["--mtu=1300"]    


vet:
  stage: vet
  script:
    - make vet
  
test:
  stage: test
  script:
    - make test

build:
  stage: build
  script:
    - make mod
    - make build

docker-build:
  stage: docker-build  
  image: docker:20.10.21
  variables:
    DOCKER_HOST: "tcp://docker:2376"
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: "1"
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  script:
    make docker_build
 